name: CI

on:
  push:
    branches: ["dev"]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-8080:latest

  deployment:
    needs: build
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script:
            docker stop web-8080
#            sleep 5
#            docker rm web-8080
#            sleep 5
#            docker pull ${{ vars.IMAGE_NAME }}
#            sleep 5
#            docker run -d -p 8080:8080 --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}

#            docker stop web-8080 &&
#              while docker container inspect web-8080 >/dev/null 2>&1; do sleep 1; done &&
#              docker rm -f web-8080
#            docker pull ${{ vars.IMAGE_NAME }}
#            docker run -d -p 8080:8080 --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}
